# Generated by Django 4.2.6 on 2024-01-15 18:20

import ServiceApp.Validators.statistic_data
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('TWITCH', 'Twitch'), ('KICK', 'Kick')], max_length=100, verbose_name='Type')),
                ('data', models.TextField(help_text='hh:mm:ss.f DD.MM.YYYY|«twitch_channel»|«twitch_account»|a/m|«message»', validators=[ServiceApp.Validators.statistic_data.validate_statistic_data], verbose_name='Data')),
                ('start', models.DateTimeField(verbose_name='Start')),
                ('end', models.DateTimeField(auto_now_add=True, verbose_name='End')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Statistic',
                'verbose_name_plural': 'Statistics',
            },
        ),
    ]
