# Generated by Django 4.2.6 on 2025-07-23 13:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('StatsApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True, verbose_name='Start Time')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='End Time')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('total_messages', models.IntegerField(default=0, verbose_name='Total Messages')),
                ('average_speed', models.FloatField(default=0.0, verbose_name='Average Speed (msg/min)')),
                ('timeouts_count', models.IntegerField(default=0, verbose_name='Timeouts Count')),
                ('total_timeout_duration', models.IntegerField(default=0, verbose_name='Total Timeout Duration (seconds)')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Shift',
                'verbose_name_plural': 'Shifts',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='TimeoutLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True, verbose_name='Start Time')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='End Time')),
                ('duration_seconds', models.IntegerField(default=0, verbose_name='Duration (seconds)')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeouts', to='StatsApp.shift', verbose_name='Shift')),
            ],
            options={
                'verbose_name': 'Timeout Log',
                'verbose_name_plural': 'Timeout Logs',
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='MessageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
                ('channel', models.CharField(max_length=100, verbose_name='Channel')),
                ('account', models.CharField(max_length=100, verbose_name='Account')),
                ('message_type', models.CharField(max_length=10, verbose_name='Message Type')),
                ('message', models.TextField(verbose_name='Message')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='StatsApp.shift', verbose_name='Shift')),
            ],
            options={
                'verbose_name': 'Message Log',
                'verbose_name_plural': 'Message Logs',
                'ordering': ['timestamp'],
            },
        ),
    ]
