# Generated by Django 4.2.6 on 2025-07-23 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StatsApp', '0002_shift_timeoutlog_messagelog'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
                ('action_type', models.CharField(choices=[('shift_start', 'Начало смены'), ('shift_end', 'Конец смены'), ('channel_select', 'Выбор канала'), ('account_select', 'Выбор аккаунта'), ('auto_start', 'Запуск авто-рассылки'), ('auto_stop', 'Остановка авто-рассылки'), ('manual_send', 'Ручная отправка'), ('settings_change', 'Изменение настроек'), ('checkbox_toggle', 'Переключение галочки'), ('frequency_change', 'Изменение частоты'), ('message_change', 'Изменение сообщения'), ('proxy_change', 'Изменение прокси'), ('work_start', 'Начало работы'), ('work_stop', 'Остановка работы'), ('error', 'Ошибка'), ('other', 'Другое')], max_length=20, verbose_name='Action Type')),
                ('description', models.TextField(verbose_name='Description')),
                ('details', models.JSONField(blank=True, null=True, verbose_name='Details')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='StatsApp.shift', verbose_name='Shift')),
            ],
            options={
                'verbose_name': 'User Action Log',
                'verbose_name_plural': 'User Action Logs',
                'ordering': ['timestamp'],
            },
        ),
    ]
