# Generated by Django 4.2.7 on 2025-08-04 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StatsApp', '0006_shift_set_frequency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shiftlog',
            name='action_type',
            field=models.CharField(choices=[('shift_start', 'Начало смены'), ('shift_end', 'Конец смены'), ('channel_select', 'Выбор канала'), ('account_select', 'Выбор аккаунта'), ('account_deselect', 'Снятие выбора аккаунта'), ('auto_start', 'Запуск авто-рассылки'), ('auto_stop', 'Остановка авто-рассылки'), ('manual_send', 'Ручная отправка сообщения'), ('message_sent', 'Сообщение отправлено'), ('message_error', 'Ошибка отправки'), ('checkbox_toggle', 'Переключение галочки'), ('frequency_change', 'Изменение частоты'), ('message_change', 'Изменение текста сообщения'), ('proxy_change', 'Изменение прокси'), ('work_start', 'Начало работы'), ('work_stop', 'Остановка работы'), ('timeout_start', 'Начало таймаута'), ('timeout_end', 'Конец таймаута'), ('settings_change', 'Изменение настроек'), ('error', 'Ошибка'), ('other', 'Другое')], max_length=50, verbose_name='Action Type'),
        ),
    ]
