version: '3.8'

services:
  streamlit:
    build: .
    volumes:
      - /root/database/:/app/database
    restart: always

  nginx:
    image: nginx:latest
    ports:
      - "8501:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/htpasswd:/etc/nginx/.htpasswd
    depends_on:
      - streamlit
    restart: always
