# Generated by Django 4.2.6 on 2024-01-15 18:20

import ProxyApp.models
import ServiceApp.Validators.twitch_token
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ProxyApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwitchAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=100, unique=True, verbose_name='Login')),
                ('token', models.CharField(help_text='oauth:«token»', max_length=100, validators=[ServiceApp.Validators.twitch_token.validate_twitch_token], verbose_name='Token')),
                ('proxy', models.OneToOneField(blank=True, default=ProxyApp.models.Proxy.get_valid_twitch_free_proxy, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='twitch_account', to='ProxyApp.proxy')),
            ],
            options={
                'verbose_name': 'Twitch Account',
                'verbose_name_plural': 'Twitch Accounts',
            },
        ),
    ]
