# Generated by Django 4.2.6 on 2025-06-02 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProxyApp', '0001_initial'),
        ('TwitchApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twitchaccount',
            name='proxy',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='twitch_account', to='ProxyApp.proxy'),
        ),
    ]
