# Generated by Django 4.2.7 on 2025-07-26 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ServiceApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('super_admin', 'Супер Админ'), ('admin', 'Админ'), ('user', 'Пользователь')], max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Роль пользователя',
                'verbose_name_plural': 'Роли пользователей',
            },
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('twitch_chatter', 'Can use Twitch Chat'), ('kick_chatter', 'Can use Kick Chat'), ('manage_kick_accounts', 'Can manage Kick accounts'), ('assign_kick_accounts', 'Can assign Kick accounts to users'), ('view_all_kick_accounts', 'Can view all Kick accounts')], 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='user',
            name='telegram',
            field=models.CharField(blank=True, max_length=100, verbose_name='Telegram'),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='ServiceApp.userrole', verbose_name='Роль'),
        ),
    ]
