# Generated by Django 4.2.6 on 2025-06-25 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KickApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kickaccount',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
