# Generated by Django 4.2.6 on 2025-06-26 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KickApp', '0002_kickaccount_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kickaccount',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='inactive', max_length=16),
        ),
    ]
