# Generated by Django 4.2.6 on 2025-06-26 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KickApp', '0003_alter_kickaccount_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='kickaccount',
            name='session_token',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
