# Generated by Django 4.2.6 on 2025-06-26 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KickApp', '0004_kickaccount_session_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kickaccount',
            name='session_token',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='kickaccount',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=16),
        ),
    ]
