# Generated by Django 4.2.6 on 2025-07-09 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KickApp', '0005_alter_kickaccount_session_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kickaccount',
            name='password',
            field=models.CharField(blank=True, help_text='Пароль от аккаунта Kick (используется только для playwright-логина)', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='kickaccount',
            name='storage_state_path',
            field=models.CharField(blank=True, help_text='Путь к storage_state playwright', max_length=400, null=True),
        ),
    ]
