# Generated by Django 4.2.6 on 2025-07-10 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KickApp', '0006_kickaccount_password_kickaccount_storage_state_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='kickaccount',
            name='storage_state_status',
            field=models.CharField(blank=True, default='pending', help_text='Статус генерации storage_state: pending/success/fail', max_length=16, null=True),
        ),
    ]
