# Generated by Django 4.2.7 on 2025-07-26 17:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('KickApp', '0007_kickaccount_storage_state_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kickaccount',
            options={'verbose_name': 'Kick аккаунт', 'verbose_name_plural': 'Kick аккаунты'},
        ),
        migrations.RemoveField(
            model_name='kickaccount',
            name='user',
        ),
        migrations.AddField(
            model_name='kickaccount',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_kick_accounts', to=settings.AUTH_USER_MODEL, verbose_name='Владелец'),
        ),
        migrations.CreateModel(
            name='KickAccountAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_type', models.CharField(choices=[('admin_assigned', 'Назначен админом'), ('self_added', 'Добавлен самостоятельно')], default='admin_assigned', max_length=20)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, verbose_name='Заметки')),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kick_accounts_assigned_by_me', to=settings.AUTH_USER_MODEL)),
                ('kick_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='KickApp.kickaccount')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kick_account_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Назначение Kick аккаунта',
                'verbose_name_plural': 'Назначения Kick аккаунтов',
                'unique_together': {('kick_account', 'user')},
            },
        ),
        migrations.AddField(
            model_name='kickaccount',
            name='assigned_users',
            field=models.ManyToManyField(related_name='assigned_kick_accounts', through='KickApp.KickAccountAssignment', to=settings.AUTH_USER_MODEL, verbose_name='Назначенные пользователи'),
        ),
    ]
