# Generated by Django 4.2.7 on 2025-07-26 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KickApp', '0009_migrate_user_to_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kickaccountassignment',
            name='assignment_type',
            field=models.CharField(choices=[('admin_assigned', 'Назначен админом')], default='admin_assigned', max_length=20),
        ),
    ]
