# Generated by Django 4.2.7 on 2025-07-28 14:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('KickApp', '0010_alter_kickaccountassignment_assignment_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='StreamerStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vid', models.CharField(max_length=100, unique=True, verbose_name='VID стримера')),
                ('status', models.CharField(choices=[('active', 'Активен'), ('inactive', 'Неактивен'), ('unknown', 'Неизвестно')], default='unknown', max_length=20, verbose_name='Статус')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Последнее обновление')),
                ('order_id', models.IntegerField(blank=True, null=True, verbose_name='ID заказа')),
                ('assigned_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Назначенный пользователь')),
            ],
            options={
                'verbose_name': 'Статус стримера',
                'verbose_name_plural': 'Статусы стримеров',
                'ordering': ['-last_updated'],
            },
        ),
        migrations.CreateModel(
            name='AutoResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('streamer_vid', models.CharField(max_length=100, verbose_name='VID стримера')),
                ('response_type', models.CharField(choices=[('chat', 'Чат сообщение'), ('donation', 'Донат сообщение'), ('subscription', 'Подписка сообщение')], default='chat', max_length=20, verbose_name='Тип ответа')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('frequency', models.IntegerField(default=60, verbose_name='Частота отправки (сек)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('priority', models.IntegerField(default=1, verbose_name='Приоритет')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Создан пользователем')),
            ],
            options={
                'verbose_name': 'Автоматический ответ',
                'verbose_name_plural': 'Автоматические ответы',
                'ordering': ['-priority', '-created_at'],
                'unique_together': {('streamer_vid', 'response_type', 'message')},
            },
        ),
    ]
