# Generated by Django 4.2.7 on 2025-07-28 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KickApp', '0011_streamerstatus_autoresponse'),
    ]

    operations = [
        migrations.CreateModel(
            name='StreamerMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supabase_id', models.IntegerField(unique=True, verbose_name='ID в Supabase')),
                ('vid', models.CharField(max_length=100, verbose_name='VID стримера')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('created_at', models.DateTimeField(verbose_name='Создано в Supabase')),
                ('last_sent', models.DateTimeField(blank=True, null=True, verbose_name='Последняя отправка')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
            ],
            options={
                'verbose_name': 'Сообщение стримера',
                'verbose_name_plural': 'Сообщения стримеров',
                'ordering': ['-created_at'],
                'unique_together': {('vid', 'message')},
            },
        ),
    ]
