# Generated by Django 4.2.7 on 2025-07-28 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('KickApp', '0012_streamermessage'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='streamermessage',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='streamermessage',
            name='streamer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='KickApp.streamerstatus', verbose_name='Стример'),
        ),
        migrations.AlterField(
            model_name='streamermessage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterUniqueTogether(
            name='streamermessage',
            unique_together={('streamer', 'message')},
        ),
        migrations.RemoveField(
            model_name='streamermessage',
            name='supabase_id',
        ),
        migrations.RemoveField(
            model_name='streamermessage',
            name='vid',
        ),
    ]
