# Generated by Django 4.2.7 on 2025-07-28 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KickApp', '0013_alter_streamermessage_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HydraBotSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='Бот включен')),
                ('message_interval', models.IntegerField(default=1, verbose_name='Интервал между циклами (сек)')),
                ('sync_interval', models.IntegerField(default=180, verbose_name='Интервал синхронизации (сек)')),
                ('max_concurrent_sends', models.IntegerField(default=1000, verbose_name='Макс. одновременных отправок')),
                ('min_message_interval', models.IntegerField(default=300, verbose_name='Мин. интервал между сообщениями (сек)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Настройки бота Гидра',
                'verbose_name_plural': 'Настройки бота Гидра',
            },
        ),
    ]
