# Generated by Django 4.2.7 on 2025-07-29 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KickApp', '0014_hydrabotsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='hydrabotsettings',
            name='cycle_interval',
            field=models.IntegerField(default=300, help_text='Интервал между полными циклами отправки всех сообщений', verbose_name='Интервал между циклами (сек)'),
        ),
    ]
