# Generated by Django 4.2.7 on 2025-07-29 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KickApp', '0015_hydrabotsettings_cycle_interval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hydrabotsettings',
            name='cycle_interval',
            field=models.IntegerField(default=3, help_text='Интервал между полными циклами отправки всех сообщений', verbose_name='Интервал между циклами (сек)'),
        ),
        migrations.AlterField(
            model_name='hydrabotsettings',
            name='message_interval',
            field=models.IntegerField(default=1, help_text='Интервал между отдельными сообщениями в одном цикле', verbose_name='Интервал между сообщениями (сек)'),
        ),
    ]
