# Generated by Django 4.2.7 on 2025-07-29 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('KickApp', '0016_alter_hydrabotsettings_cycle_interval_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='streamerstatus',
            name='is_hydra_enabled',
            field=models.BooleanField(default=False, help_text='Отправляется ли рассылка для этого стримера', verbose_name='Включен в Гидре'),
        ),
        migrations.CreateModel(
            name='StreamerHydraSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_interval', models.IntegerField(blank=True, help_text='Оставьте пустым для использования глобальных настроек', null=True, verbose_name='Интервал между сообщениями (сек)')),
                ('cycle_interval', models.IntegerField(blank=True, help_text='Оставьте пустым для использования глобальных настроек', null=True, verbose_name='Интервал между циклами (сек)')),
                ('is_active', models.BooleanField(default=True, help_text='Включена ли рассылка для этого стримера', verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('streamer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hydra_settings', to='KickApp.streamerstatus', verbose_name='Стример')),
            ],
            options={
                'verbose_name': 'Настройки Гидры для стримера',
                'verbose_name_plural': 'Настройки Гидры для стримеров',
            },
        ),
    ]
