# Generated by Django 4.2.6 on 2024-01-15 18:20

import ProxyApp.ModelsFunctional.status_manager
import ProxyApp.ModelsFunctional.twitch_account_manager
import ServiceApp.Validators.socks5_address
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proxy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(help_text='socks5://«user»:«pass»@«host»:«port»', max_length=100, unique=True, validators=[ServiceApp.Validators.socks5_address.validate_socks5_address], verbose_name='Url')),
                ('status', models.BooleanField(default=True, editable=False, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Proxy',
                'verbose_name_plural': 'Proxies',
            },
            bases=(models.Model, ProxyApp.ModelsFunctional.status_manager.ModelStatusManager, ProxyApp.ModelsFunctional.twitch_account_manager.ModelTwitchAccountManager),
        ),
    ]
